### ISSUE TITLE
vivo:totalAwardAmount

### ISSUE THREAD

**Issue by tawahle** [VIVO-DE/VIVO-languages#13]
vivo:totalAwardAmount wird als "Gesamtzahl an Auszeichnungen" übersetzt. Die Übersetzung ist nicht genau. "Gesamtbeitrag der Zuwendung" bzw. "Gesamtbeitrag der Förderung" oder einfach "Bewilligungssumme" würde hier m. E. besser passen.

**Comment by hauschke** [comment]
Ja, absolut. 

- "Förderung (Summe)"
- "Förderung (gesamt)"
- "Gesamtbeitrag der Zuwendung"
- "Bewilligungssumme"

Etwas in dieser Richtung. Hat jemand einen konkreten Vorschlag?

**Comment by hauschke** [comment]
Nach Rücksprache mit ein paar Drittmittel-ExpertInnen geht die Tendenz in Richtung "Bewilligungssumme". Gibt es dazu noch (abweichende) Meinungen aus anderen Einrichtungen?

**Comment by sonschul** [comment]
vivo:totalAwardAmount wird in der Domain Class: (Contract or Grant) genutzt.
Bei den Grants würde ich zustimmen, dass die Übersetzung "Bewilligungssumme" am ehesten passt. 
Bei den Contracts wird es vermutlich auch um andere Summen (eher "Vertragssummen") gehen, oder sieht das jemand anders?

**Comment by hauschke** [comment]
vivo:Contract:
> An agreement involving specific deliverables and payment

Wir haben vivo:totalAwardAmount das bisher nur im Grant-Zusammenhang verwendet, die Contracts waren daher nicht relevant für uns. In der Beschreibung von vivo:totalAwardAmount wird auch nur auf Grants eingegangen:

> This includes the direct cost being used for the grant activity plus indirect costs associated with administering the grant. 

Bewilligungssumme finde ich daher angemessen.
