### ISSUE TITLE
Rolle des/der nicht dauerhaft Gesandten

### ISSUE THREAD

**Issue by tawahle** [VIVO-DE/VIVO-languages#14]
<http://purl.obolibrary.org/obo/ERO_0000780> <http://www.w3.org/2000/01/rdf-schema#label> "Rolle des/der nicht dauerhaft Gesandten"@de-DE . - Die Übersetzung ist m. E. nicht korrekt. Hier ist kein Gesandter, sondern ein Einwohner gemeint. Besser wäre: "Rolle des/der nicht dauerhaften Einwohners/in"

**Comment by hauschke** [comment]
Man könnte auch fragen, warum wir das überhaupt in VIVO haben. Gibt es Verwendung dafür im Forschungsinformationskontext? Aber solange es da ist, sollten wir es besser übersetzen. Ich bin mit Deinem Vorschlag einverstanden.

**Comment by Stefan-Wolff** [comment]
Ich schließe mich Christian an.

**Comment by tawahle** [comment]
Fixed zusammen mit der Übersetzung von http://purl.obolibrary.org/obo/ERO_0000779.
