### ISSUE TITLE
vcard:Crush

### ISSUE THREAD

**Issue by tawahle** [VIVO-DE/VIVO-languages#17]
vcard:Crush wird hier als "Gedränge" übersetzt. Da es hier um einen Beziehungstyp handelt, passt die Übersetzung nicht in den Kontext. Crush kann auch als Schwarm übersetzt werden und to have a crush on smb. bedeutet - für jemanden schwärmen. Daher mein Vorschlag: vcard:Crush rdfs:label "Schwarm"@de

**Comment by hauschke** [comment]
Volle Zustimmung. Ich weiß zwar nicht, was der gewöhnliche Personalrat zur Erfassung romantischer Regungen sagt, aber wenn wir es schon übersetzen, dann auch richtig.

**Comment by tawahle** [comment]
Änderung erfolgt.
