### ISSUE TITLE
Featured in != erschienen in

### ISSUE THREAD

**Issue by hauschke** [VIVO-DE/VIVO-languages#19]
In https://github.com/VIVO-DE/VIVO-languages/blob/master/vivo-1.6/de_DE/rdf/tbox/firsttime/initialTBoxAnnotations_de_DE.n3:

`<http://vivoweb.org/ontology/core#featuredIn> <http://www.w3.org/2000/01/rdf-schema#label> "erschienen in"@de-DE .`

Hat jemand einen besseren Vorschlag? Sollen wir es evtl. in der deutschen Übersetzung bei "Featured in" belassen? Es geht hier darum, dass eine Person Gegenstand/Akteur einer Dokumentation, eines Interviews oder einer Biographie ist. Also Schriften/Werke **über** eine Person.

**Comment by hauschke** [comment]
Nach längerer, nahezu ergebnisloser Recherche habe ich folgende Vorschläge:
* "Featured in"@de-De.
* "Dargestellt in"@de-De.
* "Gegenstand von"@de-De.

**Comment by tawahle** [comment]
Änderung erfolgt.
