### ISSUE TITLE
vivo:totalAwardAmount

### ISSUE THREAD

**Issue by tawahle** [VIVO-DE/VIVO-languages#2]
http://vivoweb.org/ontology/core#totalAwardAmount wird übersetzt als "Gesamtzahl an Auszeichnungen"@de-DE 
Laut der Definion in VIVO - This includes the direct cost being used for the grant activity plus indirect costs associated with administering the grant, geht es hier weniger um Auszeichnungen, sondern um finanzielle Mitteln. Mein Übersetzungsvorschlag: Gesamtvergabebetrag bzw. Gesamtbewilligung

**Comment by hauschke** [comment]
Ich vermute, wir benötigen hier Feedback von jemandem mit BWL-Hintergrund.

**Comment by sonschul** [comment]
In #13 geklärt, oder?

**Comment by hauschke** [comment]
Richtig, dieses Ticket ist dublett.
