### ISSUE TITLE
Übersetzung von vivo:Division, vivo:Department und vivo:Laboratory

### ISSUE THREAD

**Issue by tawahle** [VIVO-DE/VIVO-languages#2]
Hi,

ihr übersetzt vivo:Division und vivo:Department als Abteilung, aber vivo:AcademicDepartment als Fachbereich. Da vivo:AcedemicDepartment eine Spezialisierung von vivo:Department ist, würde ich vorschlagen vivo:Department als Bereich zu übersetzen. 

vivo:Laboratory ist unbedingt ein Labor. In der Beschreibung zu dieser Klasse steht: "An organizational unit (as opposed to the physical facility) that performs research, provides services, or processes materials." Deshalb müsste man hier vielleicht einen anderen Begriff überlegen.

Tatiana

**Comment by tawahle** [comment]
Ich meinte vivo:Laborytory ist nicht unbedingt ein Labor!

**Comment by tawahle** [comment]
ich meinte, vivo:Laboratory ist nicht unbedingt ein Labor!

**Comment by kseuv** [comment]
vivo:Division und vivo:Department sind Klassen für solche Formen von Organisationeinheiten, die kleinere Einheiten gruppieren. Das entspricht allgemein der Bedeutung von Abteilung, Verwaltungseinheiten und ähnliches. Das ist sehr offen.

"Bereich" für eine allgemeine Übersetzung passt hier nicht, weil sich das eher auf das Themenfeld bezieht. 

Zum Labor: der wikipedia-Artikel zu Labor beschreibt es genauso wie die Ontologie: 

> Im Labor werden die verschiedenen Experimente, Prozesskontrollen, Qualitätskontrollen, Prüfungen und Messungen (insbesondere auch Kalibrierungen) durchgeführt und/oder es werden chemische Materialien bearbeitet sowie chemische Produkte hergestellt (Beispiel Chemielabor). https://de.wikipedia.org/wiki/Labor

[Anm.: Am besten immer nur ein Thema und eine Dateiangabe, wo der Begriff steht.]

**Comment by tawahle** [comment]
Wenn es keine Unterschiede zwischen Division und Department geben würde, gäbe es nur eine von beiden Klassen. Es gibt sicherlich inhaltlich Unterschiede zwischen diesen beiden Begriffen.
In der deutschen Version ist es außerdem verwirrend, wenn es da zweimal vivo:Abteilung gibt. 

"Bereich" muss nicht unbedingt fachbezogen sein. In unserer Einrichtung ist ein Bereich - die Untereinheit der Abteilung, z.B. Abteilung Forschung und Entwicklung, Bereich Forschung, Bereich Entwicklung. 

Die VIVO-Beschreibung von Labor sagt ja auch: "as opposed to the physical facility ". Deshalb, ist damit nicht unbedingt ein Labor im eigentlichen Sinne gemeint, wie es z.B. in der Wikipedia beschrieben ist.

**Comment by kseuv** [comment]
Du kannst immer einen konkreten Vorschlag machen. bzw. es in den lokalen Übersetzungen anpassen.

Dein Beispiel zeigt, dass in eurer Einrichtung eine andere Auffassung herrscht als z.B. an der TU Dresden, wo ein Bereich etwas anderes ist. Deswegen sind diese sehr allgemeinen Klassen auch allgemein benannt. Das ist ein Thema für das Glossar ... 

Ich schrieb nicht "fachbezogen" sondern themenbezogen. 

-- Zum Labor: was sollte es denn deinem Verständnis nach sein? Mache bitte einen konkreten Vorschlag. Ich sehe keinen Unterschied und kenne auch keinen besseren Begriff.
Der englische Text betont lediglich den Aspekt als Organisationseinheit.

**Comment by tawahle** [comment]
-- **Division** - "A major unit or section within a larger organization."
**Department** - "A unit within a larger organization that addresses a specific subject or area of activity." Demnach, kann Division - als Abteilung, Department - als Unterabteilung übersetzt werden, wenn Bereich, deiner Meinung nach, zu TIB-spezifisch ist.
-- Vorschlag: **Labor** - Arbeitsgruppe
 Laut C. H. soll das Glossar den Stand der Dinge abbilden und Diskussionen in Issues geführt werden. Bald ist wieder ein Call, dann können wir das noch mal besprechen.

**Comment by kseuv** [comment]
Wir haben das spaßeshalber an realen Beispielen geprüft: an manchen amerikanischen Unis wird Division so gebraucht, an manchen Department anders. Bei beiden Begiffen handelt es sich um **allgemeine Begriffe**, um Organisationen zu gliedern.

Eine hierarchische Anordnung ergibt sich weder aus den Beschreibungen der Ontologie, noch aus dem realen Gebrauch. 

Vielmehr ist es doch so, dass du für deine Instanz eine eigene Regelung finden kannst, wie du Divison oder Department verwenden und übersetzen willst.

--- Laboratory ist keine Arbeitsgruppe.

**Comment by hauschke** [comment]
Beschluss aus dem [Ontologie-Call vom 27.02.2017](https://github.com/VIVO-DE/vivo-de-ontology-extension/wiki/Ontologie-Call-2017-02-27): 

vivo:Division = Bereich
vivo:Department = Abteilung
vivo:Laboratory = Labor
