### ISSUE TITLE
outreachOverview = Überblick Wissenschaftskommunikation?

### ISSUE THREAD

**Issue by hauschke** [VIVO-DE/VIVO-languages#20]
Bisher übersetzt mit "Gesamtdarstellung Der Öffentlichkeitsarbeit". Das passt aber m.E. nicht.

Meine Vorschläge:
- Überblick Wissenschaftskommunikation
- Wissenschaftskommunikation (Überblick/gesamt)

Besten Dank an [@FrueheNeuzeit](https://twitter.com/FrueheNeuzeit/status/956195543155388417)!

**Comment by tawahle** [comment]
Änderung erfolgt.
