### ISSUE TITLE
reportId

### ISSUE THREAD

**Issue by tawahle** [VIVO-DE/VIVO-languages#21]
<http://vivoweb.org/ontology/core#reportId> <http://www.w3.org/2000/01/rdf-schema#label> "Gutachten-Identifier"@de-DE . 
Da wir bibo:Report als "Report"@de übersetzten, sollte auch die dazugehörige Property statt "Gutachten-Identifier", "Report-ID" bzw. "Report-Identifier" übersetzt werden.

**Comment by hauschke** [comment]
Aus der VIVO-Ontologie: "Unique identifier for a Report (a type of information resource)."

Ich bin für Report-Identifier. Förderkennzeichen passt nicht, das es sich auf die Förderung und nicht auf den Report an sich bezieht. Gibt es noch bessere Ideen?

**Comment by tawahle** [comment]
Änderung erfolgt.
