### ISSUE TITLE
"Fähigkeitskarte"

### ISSUE THREAD

**Issue by Stefan-Wolff** [VIVO-DE/VIVO-languages#22]
display:CapabilityMapMenuItem display:linkText "Fähigkeitskarte"@de-DE .
display:CapabilityMap display:title "Fähigkeitskarte"@de-DE .

Bis bessere Vorschläge vorliegen bin ich für: **Themenkarte**

**Comment by hauschke** [comment]
Wir haben hier zwei inhaltliche Komponenten:
- Capability
- Map

Ich sehe die Map eher nicht als Karte, eine Verortung findet m.E. nicht statt. Ich sehe die Visualisierung eher als Netz(werk).

Vielleicht  "Kompetenznetzwerk"? Wobei sowohl Themen als auch Kompetenzen nicht wirklich dem entsprechen, was ich in der Visualisierung sehe. Themen noch ein bißchen eher. "Themennetz" o.ä. versteht aber auch niemand.  

Themenkarte ist aber schon mal besser als Fähigkeitskarte, da gebe ich Dir Recht.

**Comment by sonschul** [comment]
Ich würde gerne die Begriffe "Forschungsnetz(werk)" oder "Forschernetzwerk" vorschlagen, da an dieser Stelle in VIVO die Suchbegriffe/Konzepte mit den jeweiligen Forscherprofilen visualisiert werden. 
Themen würde bei uns eher auf die Schlagworte zu Personen bzw. Projekte zutreffen.

**Comment by grahamtriggs** [comment]
So, this originally come from Melbourne. I can't attest that this is how it has always been, but their current Find an Expert uses the term "Capability Map" in the title of the visualisation, however, the links to it refer to a "network diagram of the terms [below]"

**Comment by Stefan-Wolff** [comment]
Beide Vorschläge finde ich gut, sehe aber auch Gründe, die gegen sie sprechen:
"Forschungsnetzwerk" trifft es inhaltlich ganz gut, klingt in meinen Ohren allerdings etwas holprig.
"Forschernetzwerk" trifft m.E. den Inhalt der Visualisierung nicht, da die enthaltenen Forscher durch ihre Forschungsthemen verknüpft werden, aber keine Kooperationen/Partnerschaften dargestellt werden. Man sieht somit eben kein Personennetzwerk.

Zu "Netz" vs. "Netzwerk": Ich finde, dass "Netz" im Deutschen eher an ein Spinnennetz erinnert. Ich schreibe ihm eher die Funktion des Auffangens oder Sammelns zu, als die der Verknüpfung bestimmter Elemente. Deshalb finde ich "Netzwerk" hier passender.

**Comment by tawahle** [comment]
Wie wäre es mit Forschungsthemennetzwerk? Wie gut, dass man in der deutschen Sprache beliebig viele Wörter aneinanderreihen kann. :-)

**Comment by Stefan-Wolff** [comment]
Dann aber gleich Forschungsthemennetzwerkgraph ;-)

**Comment by sonschul** [comment]
In der letzten Version hieß es bei uns "Wissenschaftslandkarte" ;-)

**Comment by hauschke** [comment]
Okay. "Wissenschaftsforschungs- und Lehrenthemennetzwerkgraphenlandkartenvisualisierung" wäre mein Kompromissvorschlag. 

Wissenschaftslandkarte finde ich zwar griffig, aber da empfinde ich die Verwechslungsgefahr mit der Map of Science ein bißchen zu hoch: https://vivo.tib.eu/fis/vis/map-of-science/n0000-0003-1160-8727

**Comment by dofeldsc** [comment]
Meine Favoriten sind "Forschungsnetzwerk" oder "Forschungsnetz"

**Comment by hauschke** [comment]
Kompetenznetz fällt mir gerade noch ein.

**Comment by tawahle** [comment]
"Kompetenznetz" ist zumindest am nähsten zur Capability Map. An dieser Stelle würde ich noch mal den Vorschlag von [Stefan-Wolff](https://github.com/Stefan-Wolff) aufgreifen: **Themenkarte**.

**Comment by hauschke** [comment]
Nach Abstimmung in Slack scheint der Trend in Richtung Forschungsnetz zu weisen. Ich werde das nun umsetzen. Sollte das nicht auf Einverständnis stoßen, sollten wir das vielleicht in einer Videokonferenz thematisieren. Ich glaube, wir sind uns einig, dass Forschungsnetz zumindest besser ist als die aktuelle Übersetzung "Fähigkeitskarte".

**Comment by hauschke** [comment]
Bis auf weiteres geschlossen. Bitte bei Bedarf wieder öffnen.
