### ISSUE TITLE
vivo:dateTimeInterval

### ISSUE THREAD

**Issue by tawahle** [VIVO-DE/VIVO-languages#24]
vivo:dateTimeInterval wird aktuell übersetzt als Datum/Uhrzeit-Intervall.
M.E. würde hier "Zeitspanne" oder "Zeitraum" besser passen.

**Comment by hauschke** [comment]
Zeit-/Datumsintervall wird anscheinend im IT-Kontext ab und an eingesetzt. Wir konnten nach Erinnerung und Stichproben keine Stelle finden, an der das für "normale" Nutzer sichtbar ist. Kann das jemand bestätigten oder widerlegen? Falls das wirklich nur Editors and above betrifft, würde ich für eine möglicherweise komplizierte, aber technisch korrekte Bezeichnung bevorzugen. In dem Falle würde ich für "Zeit-/Datumsintervall" stimmen. Ist es für Self-Editors oder Public sichtbar, stimme ich für "Zeitspanne" oder "Zeitintervall".

**Comment by sonschul** [comment]
Die Übersetzung für "date/time interval" wird auf den Forschungsprojekt-Seiten (Grants) und den Events auch für normale Nutzer angezeigt. Wir würden daher für "Zeitintervall" oder "Zeitraum" plädieren.

**Comment by tawahle** [comment]
Das ist korrekt, die Zeitangabe ist (wenn nicht anders eingestellt) auch für nicht eingeloggte Nutzer sichtbar, s. https://vivo.tib.eu/fis/display/drmpro1751. "Dauer" würde sowohl in Bezug auf Projekte, als auch auf Events und Rollen auch gut passen.

**Comment by hauschke** [comment]
Ja, richtig. Ich korrigiere das nun auf Zeitraum. Das ist ein gängiger und semantisch passender Begriff.
