### ISSUE TITLE
vivo:ClinicalRole = "klinische Position"

### ISSUE THREAD

**Issue by hauschke** [VIVO-DE/VIVO-languages#3]
Die Bezeichnungen der Rollen sollten insgesamt einmal durchgesehen und ggf. überarbeitet werden. Besonders deutlich wird dies aber bei der sog. "klinischen Position". Vorschläge?

**Comment by dofeldsc** [comment]
An sich sind die Labels auf dem Commit passend nur leider hat sich bei dem Label "edit_entry_for_outreach_provider_role" auch die englische Bezeichnung eingeschlichen.

In den Sprachdateien steht jetzt "Diese Öffentlichkeitsarbeitsrolle bearbeiten Edit this outreach provider role"

**Comment by hauschke** [comment]
> 
> 
> An sich sind die Labels auf dem Commit passend nur leider hat sich bei dem Label "edit_entry_for_outreach_provider_role" auch die englische Bezeichnung eingeschlichen.
> 
> In den Sprachdateien steht jetzt "Diese Öffentlichkeitsarbeitsrolle bearbeiten Edit this outreach provider role"

Das ist zwischenzeitlich behoben worden.

Wenn hier sonst keine aktuelle Not besteht, mache ich das Ticket zu. Sollte Diskussionsbedarf bestehen, können wir für spezifische Änderungswünsche neue Issues aufmachen,
