### ISSUE TITLE
outreach_comm_service = outreach & community service

### ISSUE THREAD

**Issue by hauschke** [VIVO-DE/VIVO-languages#4]
https://github.com/VIVO-DE/VIVO-languages/blob/master/webapp/src/main/webapp/i18n/vivo_all_de_DE.properties

Zeilen 271-272 
```
outreach_comm_service = Öffentlichkeitsarbeit und Gemeindedienst
outreach_comm_service_in = Öffentlichkeitsarbeit und Gemeindedienst in
```

Ich habe dies provisorisch verbessert in
```
outreach_comm_service = Öffentlichkeitsarbeit und Community-Arbeit
outreach_comm_service_in = Öffentlichkeitsarbeit und Community-Arbeit in
```
Dies klingt zwar immer noch holprig, ist aber m.E. schon deutlich besser als die bisherige Fassung. Wir sollten und auf eine abgestimmte Übersetzung einigen.

**Comment by dofeldsc** [comment]
Finden wir auch gut! Die Änderungen wurden ja auch schon eingebaut
