### ISSUE TITLE
localAwardId

### ISSUE THREAD

**Issue by tawahle** [VIVO-DE/VIVO-languages#6]
vivo:localAwardId wird aktuell als ID für die Auszeichnung übersetzt. Laut Definition in VIVO ist localWardId - "An institution's local identifier assigned to a grant awarded." und hat demnach nichts mit einer Auszeichnung zu tun, sondern eher mit Fördermittel.

**Comment by hauschke** [comment]
"Lokales Förderkennzeichen" wäre sachlich vermutlich korrekt, klingt aber etwas holprig. Gibt es bessere Vorschläge?

**Comment by sonschul** [comment]
Bessere Vorschläge leider nicht, aber eventuell könnte man statt "lokales Förderkennzeichen" 
den Begriff "Internes Förderkennzeichen" verwenden.

**Comment by tawahle** [comment]
Wie wäre es mit "internes Förder-ID"?
