### ISSUE TITLE
vivo:Grant und zugehörige Properties

### ISSUE THREAD

**Issue by tawahle** [VIVO-DE/VIVO-languages#7]
<http://vivoweb.org/ontology/core#Grant> <http://www.w3.org/2000/01/rdf-schema#label> "Stipendium"@de-DE . 
<http://vivoweb.org/ontology/core#grantSubcontractedThrough> <http://www.w3.org/2000/01/rdf-schema#label> "Subunternehmervertrag durch"@de-DE .
<http://vivoweb.org/ontology/core#grantDirectCosts> <http://www.w3.org/2000/01/rdf-schema#label> "Direkte Kosten"@de-DE .
<http://vivoweb.org/ontology/core#subcontractsGrant> <http://www.w3.org/2000/01/rdf-schema#label> "Teil eines übergeordneten Forschungsprojektes"@de-DE .
In jedem dieser Tripel wird Grant in einem anderen Kontext übersetzt oder gar ausgelassen. Die Übersetzung sollte harmonisiert werden.

**Comment by kseuv** [comment]
Ja, die sind schräg!
 
Frage: "Stipendium" sollte besser "Drittmittel" heißen?

Bei den Properties handelt es sich um (holprige) Übersetzungen der Label, nicht des Property-Namens:

* subcontracted through = [Drittmittel] mit einem Untervertrag verbunden durch
* direct costs = Direkte Kosten
* subcontracts grant = ist durch ein Untervertrag verbunden [mit diesem Drittmittel]

Gibt es dazu einen Kontext?

**Comment by tawahle** [comment]
Ich bin mir nicht sicher, dass Grant als Drittmittel übersetzt werden kann.

**Comment by tawahle** [comment]
Ich bin für Zuwendung, Zuschuss oder Förderung. Es können doch auch interne Organisationseinheiten die Förderung gewähren. In dem Fall sind es keine Drittmittel.

- Grant = Förderung
- subcontractedThrough = [Förderung] durch einen Untervertrag verbunden mit [Organisation]
- direct costs = Direkte Kosten (meinetwegen)
- subcontracts grant = gewährt Förderung durch einen Untervertrag (hier kann man sicherlich noch eine bessere Lösung finden!)

**Comment by tawahle** [comment]
Änderung erfolgt.
