### ISSUE TITLE
sponsorAwardId

### ISSUE THREAD

**Issue by tawahle** [VIVO-DE/VIVO-languages#7]
vivo:sponsorAwardId wird aktuell als "Id für den Sponsor der Auszeichnung" übersetzt. Passender wäre evtl. die Übersetzung "Id des Fördermittelgebers" o. Ä.

**Comment by hauschke** [comment]
"Förderkennzeichen" wäre sachlich richtig. Wichtig wäre die Trennung von localAwardId.
