### ISSUE TITLE
vivo:affiliatedOrganization

### ISSUE THREAD

**Issue by tawahle** [VIVO-DE/VIVO-languages#8]
vivo:affiliatedOrganization wird als "Mitgliedsorganisation" übersetzt. Mitgliedsorganisation setzt eine Mitgliedschaft in einem Verband o. Ä. voraus und es ist hier nicht unbedingt gemeint.

**Comment by sonschul** [comment]
Eventuell passt "verbundene Organisation" oder "assoziierte Organisation" besser. 
Mitgliedsorganisation halte ich an dieser Stelle auch nicht für passend.

**Comment by tawahle** [comment]
Ist "affilierte Organisation" auch im Deutschen gängig?

**Comment by hauschke** [comment]
Nein, eigentlich nicht. 

- angehörig
- assoziiert
- verbunden
- angeschlossen

So richtig trifft es das nicht, oder? Gibt es noch weitere Vorschläge?

**Comment by tawahle** [comment]
Wie wäre es mit "zugehörige Organisation"?

**Comment by tawahle** [comment]
Da Affliation als Zugehörigkeit übersetzt wird - s. https://www.orcid-de.org/wer-autorin-sagt-muss-auch-zugehoerigkeit-sagen-entwicklungen-aus-der-organization-identifier-working-group/, scheint "**zugehörige Organisation**" als Übersetzung für "**affiliated organization**" am passendsten zu sein.

**Comment by hauschke** [comment]
Mit https://github.com/VIVO-DE/VIVO-languages/commit/9709da0f8b42e1c4caf90f5febfa5d1bf6bf584e gelöst.
