### ISSUE TITLE
vivo:geographicFocusOf

### ISSUE THREAD

**Issue by tawahle** [VIVO-DE/VIVO-languages#9]
vivo:geographicFocusOf wird als "Ort von" übersetzt. Gemeint wird hier eher der geographische Schwerpunkt z.B. eines Events.

**Comment by dofeldsc** [comment]
Ja stimmt, die jetzige Übersetzung passt nicht wirklich. Wir wären für "geographischer Fokus" oder "geographischer Schwerpunkt"

**Comment by hauschke** [comment]
"Geographischer Fokus" trifft es, ist ja auch recht direkt übersetzt. Ich mache das nun.

**Comment by hauschke** [comment]
- angeschlossene Organisation
-
